"""Complete chat database with relationships

Revision ID: 0251b0b5fc8a
Revises: 
Create Date: 2025-09-08 00:00:28.032994

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0251b0b5fc8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversation', 'message', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    # ### end Alembic commands ###
